### ISSUE TITLE
Actions failed to run

### ISSUE THREAD

**Issue by khairuladib94** [cess-lab/pi2-auto-detection#2]
Salam @syaifulafrizal,

Saya perasan GitHub Actions asyik failed je berturut2 (https://github.com/cess-lab/pi2-auto-detection/actions):
![image](https://github.com/cess-lab/pi2-auto-detection/assets/70192529/b94b5088-d4b6-4a16-8cc7-5aae43722039)
Saya tengok punca errornya (click pada salah satu failed workflow tu dan check step yang produce error):
![image](https://github.com/cess-lab/pi2-auto-detection/assets/70192529/862277bf-289b-488c-8f3f-a93e9a89a056)
Macam ada kaitan dengan function `cdfread` dalam file `StartPrediction.m`, tapi tak tahu kenapa boleh error. Syaiful tolong tengokkan bila2 free.

Thanks

**Comment by khairuladib94** [comment]
Terima kasih tengokkan @syaifulafrizal. Yang dia tunjuk 3 stations tu sebab 3 stations je ada data atau/dan ada Pi2 pada run kali ni. Yang pasal station HON tu saya tak pasti kenapa, maybe la dia punca. Maybe ada error pada data HON.

**Comment by syaifulafrizal** [comment]
![image](https://github.com/cess-lab/pi2-auto-detection/assets/114385927/8a289e05-7ada-4ead-8558-2d217b95d1c1
Okay dh settle

**Comment by khairuladib94** [comment]
Ok mantap @syaifulafrizal Thanks!
